{{ if or .loki.enabled-}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keda
  namespace: infra
spec:
  interval: 60m
  url: https://kedacore.github.io/charts
{{- end }}