---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 10m
  values:
    controller:
      service:
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      defaultBackend:
        enabled: true
        replicaCount: 2
