---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: infra
spec:
  interval: 60m
  releaseName: keda
  chart:
    spec:
      chart: ingress-nginx
      version: 2.9.3
      sourceRef:
        kind: HelmRepository
        name: keda
      interval: 10m