---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: 2.9.2
      sourceRef:
        kind: HelmRepository
        name: keda
      interval: 10m      
