apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: deploy-key-youcefguichi-gimlet-boostraping-tutourial
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
    c2gtZWQyNTUxOQAAACADJQlSsW/q16+JEoRgZH+XRhC9FjodD/DrkvEimGJnYQAA
    AJjYnQiD2J0IgwAAAAtzc2gtZWQyNTUxOQAAACADJQlSsW/q16+JEoRgZH+XRhC9
    FjodD/DrkvEimGJnYQAAAEAEuQyGoYA5hWQi3xYAdL+CEwWMs96OMlhJmEIf7gjh
    yAMlCVKxb+rXr4kShGBkf5dGEL0WOh0P8OuS8SKYYmdhAAAAEGtleWdlbkBnaW1s
    ZXQuaW8BAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAMlCVKxb+rXr4kShGBkf5dGEL0WOh0P8OuS8SKYYmdh
  known_hosts: |
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
